"""first_migration

Revision ID: 3c7e938cdc3f
Revises: 
Create Date: 2024-10-19 16:38:46.286228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c7e938cdc3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='テストアイテムID'),
    sa.Column('field1', sa.String(length=20), nullable=False, comment='field1'),
    sa.Column('tield2', sa.String(length=20), nullable=False, comment='tield2'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp'), nullable=False, comment='作成日時'),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp on update current_timestamp'), nullable=False, comment='更新日時'),
    sa.PrimaryKeyConstraint('id'),
    comment='テストアイテム'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_items')
    # ### end Alembic commands ###
