"""images_migration

Revision ID: 46db3b6ebc51
Revises: 4cae46032682
Create Date: 2024-10-19 18:05:31.646052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46db3b6ebc51'
down_revision = '4cae46032682'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
