"""second_migration

Revision ID: 4cae46032682
Revises: 3c7e938cdc3f
Create Date: 2024-10-19 17:59:19.301162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cae46032682'
down_revision = '3c7e938cdc3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
