"""fix_images_migration

Revision ID: 65ff834a7af5
Revises: 46db3b6ebc51
Create Date: 2024-10-19 18:08:05.763779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65ff834a7af5'
down_revision = '46db3b6ebc51'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
