"""fix_images_migration

Revision ID: e8d0e2967243
Revises: 65ff834a7af5
Create Date: 2024-10-19 18:10:18.348644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8d0e2967243'
down_revision = '65ff834a7af5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='画像テーブルのID'),
    sa.Column('image_path', sa.String(length=256), nullable=False, comment='画像のパス'),
    sa.Column('latitude', sa.Double(), nullable=True, comment='緯度'),
    sa.Column('longitude', sa.Double(), nullable=True, comment='経度'),
    sa.Column('happiness_point', sa.Integer(), nullable=True, comment='幸福度ポイント'),
    sa.Column('happiness_text', sa.String(length=1024), nullable=True, comment='幸福度テキスト'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='作成日時'),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp on update current_timestamp'), nullable=False, comment='更新日時'),
    sa.PrimaryKeyConstraint('id'),
    comment='画像用のテーブル'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
